<Project Sdk="Tomat.Terraria.ModLoader.Sdk">

    <PropertyGroup>
      <RootNamespace>Daybreak.Hooks</RootNamespace>
    </PropertyGroup>

    <Import Project="../Module.props"/>

    <ItemGroup>
        <ProjectReference Include="..\Daybreak.EarlyLoader.V1\Daybreak.EarlyLoader.V1.csproj" />
    </ItemGroup>

</Project>