<Project Sdk="Tomat.Terraria.ModLoader.Sdk">

    <Import Project="../Module.props"/>

    <ItemGroup>
        <ProjectReference Include="..\Daybreak.Hooks.V1\Daybreak.Hooks.V1.csproj"/>
        <ProjectReference Include="..\Daybreak.Rendering.V1\Daybreak.Rendering.V1.csproj"/>
    </ItemGroup>

</Project>